name: Deploy
on:
  push:
    branches:
      - main
# ADD THIS BLOCK BELOW
permissions:
  contents: read
  deployments: write
# --------------------
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'southafricanbotanical'
          directory: 'dist'
